version: "3.9"
services:
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - /mnt/hdd/redis:/data
        entrypoint: redis-server --appendonly yes
        restart: always
    bitcoind:
        image: bitcoind
        build:
            context: bitcoind
            dockerfile: Dockerfile
        command: bitcoind
        restart: always
        ports:
            - "8332:8332"
            - "8333:8333"
            - "28332:28332"
            - "28333:28333"
        volumes:
            - /mnt/hdd/bitcoin:/root/.bitcoin
    lnd:
        image: lnd
        build:
            context: lnd
            dockerfile: Dockerfile
        depends_on:
            - bitcoind
        command: lnd
        restart: always
        ports:
            - "10009:10009"
        volumes:
            - /mnt/hdd/lnd:/root/.lnd
    hub:
        image: hub
        build:
            context: hub
            dockerfile: Dockerfile
        depends_on:
            - bitcoind
            - lnd
            - redis
        command: node build/index.js
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - /mnt/hdd/hub/config.js:/opt/LndHub/config.js
            - /mnt/hdd/lnd/data/chain/bitcoin/mainnet/admin.macaroon:/opt/LndHub/admin.macaroon
            - /mnt/hdd/lnd/tls.cert:/opt/LndHub/tls.cert