version: "3.3"
services:
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - /mnt/hdd/redis:/data
        entrypoint: redis-server --appendonly yes --requirepass moneyprintergobrrr
        restart: always
    core:
        image: bitcoind
        build:
            context: bitcoind
            dockerfile: Dockerfile
        command: bitcoind
        restart: always
        # zero mq doesn't bind to docker network
        network_mode: "host"
        #ports:
        #    - "8332:8332"
        #    - "8333:8333"
        #    - "28332:28332"
        #    - "28333:28333"
        volumes:
            - /mnt/hdd/bitcoin:/root/.bitcoin
            - /run/tor:/run/tor
    lnd:
        image: lnd
        build:
            context: lnd
            dockerfile: Dockerfile
        #depends_on:
        #    - bitcoind
        command: lnd
        restart: always
        network_mode: "host"
        #ports:
        #    - "10009:10009"
        #    - "8080:8080"
        volumes:
            - /mnt/hdd/lnd:/root/.lnd
            - /run/tor:/run/tor
    hub:
        image: hub
        build:
            context: hub
            dockerfile: Dockerfile
        #depends_on:
        #    - bitcoind
        #    - lnd
        #    - redis
        #command: node build/index.js
        command: tail -f /dev/null
        restart: always
        network_mode: "host"
        #ports:
        #    - "3000:3000"
        volumes:
            - /mnt/hdd/lnd:/lnd:ro
        environment:
            CONFIG: ${HUBCONFIG}
            TLSCERT: "/lnd/tls.cert"
            MACAROON: "/lnd/data/chain/bitcoin/mainnet/admin.macaroon"
