version: "3.9"
services:
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - /mnt/hdd/redis:/data
        entrypoint: redis-server --appendonly yes --requirepass moneyprintergobrrr
        restart: always
    bitcoind:
        image: bitcoind
        build:
            context: bitcoind
            dockerfile: Dockerfile
        command: bitcoind
        restart: always
        ports:
            - "8332:8332"
            - "8333:8333"
            - "28332:28332"
            - "28333:28333"
        volumes:
            - /mnt/hdd/bitcoin:/root/.bitcoin
    lnd:
        image: lnd
        build:
            context: lnd
            dockerfile: Dockerfile
        depends_on:
            - bitcoind
        command: lnd
        restart: always
        ports:
            - "10009:10009"
            - "8080:8080"
        volumes:
            - /mnt/hdd/lnd:/root/.lnd
    hub:
        image: hub
        build:
            context: hub
            dockerfile: Dockerfile
        depends_on:
            - bitcoind
            - lnd
            - redis
        links:
            - bitcoind
            - lnd
            - redis
        command: node build/index.js
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - /mnt/hdd/hub/config.js:/opt/LndHub/config.js:ro
            - /mnt/hdd/lnd:/lnd:ro
        environment:
            CONFIG: '{ "rateLimit": 10000, "postRateLimit": 10000, "redis": { "port": 6379, "host": "redis", "family": 4, "password": "moneyprintergobrrr", "db": 0 }, "lnd": { "url": "lnd:10009", "password":""}}'
            TLSCERT: "/lnd/tls.cert"
            MACAROON: "/lnd/data/chain/bitcoin/mainnet/admin.macaroon"
