version: "2.4"
services:
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - /mnt/hdd/redis:/data
        entrypoint: redis-server --appendonly yes --requirepass moneyprintergobrrr
        restart: always
        cpus: 0.5
        mem_limit: 50M
    core:
        image: bitcoind
        build:
            context: bitcoind
            dockerfile: Dockerfile
        command: bitcoind
        restart: always
        # zero mq doesn't bind to docker network
        network_mode: "host"
        #ports:
        #    - "8332:8332"
        #    - "8333:8333"
        #    - "28332:28332"
        #    - "28333:28333"
        volumes:
            - /mnt/hdd/bitcoin:/root/.bitcoin
            - /run/tor:/run/tor
        cpus: 0.5
        mem_limit: 75M
    lnd:
        image: lnd
        build:
            context: lnd
            dockerfile: Dockerfile
        #depends_on:
        #    - core
        command: lnd --tor.active --tor.v3 --listen=localhost
        restart: always
        network_mode: "host"
        #ports:
        #    - "10009:10009"
        #    - "8080:8080"
        volumes:
            - /mnt/hdd/lnd:/root/.lnd
            - /run/tor:/run/tor
        cpus: 1
        mem_limit: 512M
        mem_reservation: 512M
    hub:
        image: hub
        build:
            context: hub
            dockerfile: Dockerfile
        #depends_on:
        #    - core
        #    - lnd
        #    - redis
        command: node build/index.js
        #command: tail -f /dev/null
        restart: always
        network_mode: "host"
        #ports:
        #    - "3000:3000"
        volumes:
            - /mnt/hdd/lnd/tls.cert:/opt/LndHub/tls.cert:ro
            - /mnt/hdd/lnd/data/chain/bitcoin/mainnet/admin.macaroon:/opt/LndHub/admin.macaroon:ro
        cpus: 0.5
        mem_limit: 100M
        environment:
            CONFIG: ${HUBCONFIG}
